# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 923f83004792b61c52c40eadd875c2e36e0d10c0550bbb09e404a4f0b9d4f98c4d61100503fbf6f02b1e38030a19dfa3ce5e0039191e419589b6778ba83ae51f

test:
  secret_key_base: 8510b1ee50ca067db382d153bea17991f3aa170756423daa73f208e532f9f930f3217664761f2ed99f02a6ea75f5f6d8da51ca371f52cb3fea6ff3e6376f6dcf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
